x-common-variables: &common-env
  ASPNETCORE_ENVIRONMENT: Development
  JWT_ISSUER: ${JWT_ISSUER}
  JWT_AUDIENCE: ${JWT_AUDIENCE}
  JWT_KEY: ${JWT_KEY}

x-common-args: &common-args
    GITHUB_USERNAME: ${GITHUB_USERNAME}
    GITHUB_TOKEN: ${GITHUB_TOKEN}

services:
  angular-ui:
    build:
      context: ../todo.angular-client/
      dockerfile: Dockerfile.local
    depends_on:
      - gateway
    volumes:
      - ../todo.angular-client:/app
      - /app/node_modules

  gateway:
    build:
      context: ../todo.gateway/
      dockerfile: Dockerfile.local
      args:
        <<: *common-args
    ports:
      - "8080:8080"
    volumes:
      - ../todo.gateway/src:/app/src
    depends_on:
      - auth-service
      - task-service
      - analytics-service
      - recommendations-service
    environment:
      <<: *common-env

  auth-service:
    build:
      context: ../todo.auth-service/
      dockerfile: Dockerfile.local
      args:
        <<: *common-args
    volumes:
      - ../todo.auth-service/src:/app/src
    depends_on:
      - db
    environment:
      <<: *common-env
      SQL_CONNECTION_STRING: ${SQL_CONNECTION_STRING_AUTH}
  
  task-service:
    platform: linux/amd64
    build:
      context: ../todo.task-service/
      dockerfile: Dockerfile.local
      args:
        <<: *common-args
    volumes:
      - ../todo.task-service/src:/app/src
    depends_on:
      - db
    environment:
      <<: *common-env
      SQL_CONNECTION_STRING: ${SQL_CONNECTION_STRING_TASK}

  analytics-service:
    build:
      context: ../todo.analytics/
      dockerfile: Dockerfile.local
    depends_on:
      - task-service
      - db
    environment:
      <<: *common-env
      SQL_URL: ${SQL_CONNECTION_STRING_ANALYTICS}
      SQL_USERNAME: ${SQL_USERNAME}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DDL_AUTO: update
      SQL_DRIVER: org.postgresql.Driver
      SQL_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  recommendations-service:
    build:
      context: ../todo.recommendations/
      dockerfile: Dockerfile.local
    environment:
      <<: *common-env
      SQL_CONNECTION_STRING: ${SQL_CONNECTION_STRING_RECOMMENDATIONS}
    depends_on:
      - db
    volumes:
      - ../todo.recommendations/src/app:/app/src/app

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - ../todo.db/data:/var/lib/postgresql/data
      - ../todo.db/init:/docker-entrypoint-initdb.d/