apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}