apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-common-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}