name: Build and Release Infra Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OCI_REPO: ghcr.io/abstractize
  PROJECT_NAME: todo
  CHART_NAME: infra

jobs:
  helm-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Update Chart.yaml version and appVersion
        run: |
          VERSION="0.1.${GITHUB_RUN_NUMBER}"
          yq -y -i ".appVersion = \"${GITHUB_SHA}\" | .version = \"$VERSION\"" .helm/Chart.yaml

      - name: Lint Helm chart
        run: helm lint .helm

      - name: Package Helm chart
        run: helm package .helm --destination .helm-dist

      - name: Push Helm chart to GHCR (OCI)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          CHART_FILE=$(ls .helm-dist/*.tgz)
          helm push $CHART_FILE oci://${{ env.OCI_REPO }}/helm-charts/${{ env.PROJECT_NAME }}