name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm lint
        run: helm lint .helm